cd /home/ec2-user/digital_esign

git config --global --add safe.directory /home/ec2-user/digital_esign
git pull

sudo podman stop digital-esign || true
sudo podman rm digital-esign || true

# ðŸ”¥ REMOVE OLD IMAGE FIRST
sudo podman rmi digital-esign-ui || true

# ðŸ”¥ NOW BUILD
sudo podman build --no-cache -t digital-esign-ui .

sudo podman run -d -p 80:80 --name digital-esign digital-esign-ui